"""
Hebrew city/zone name → English translation.

Lookup order in transforms.py:
  1. Exact match
  2. Strip trailing " NNN" digits and retry
  3. Strip " - Suffix" and retry on base city name
  4. Fall back to original Hebrew text
"""

LOCATION_MAP: dict[str, str] = {
    # ── Tel Aviv metro ──────────────────────────────────────────────
    "תל אביב": "Tel Aviv",
    "תל אביב - מרכז העיר": "Tel Aviv - City Center",
    "תל אביב - צפון": "Tel Aviv - North",
    "תל אביב - דרום": "Tel Aviv - South",
    "תל אביב - מזרח": "Tel Aviv - East",
    "תל אביב - יפו": "Tel Aviv - Jaffa",
    "יפו": "Jaffa",
    "רמת גן": "Ramat Gan",
    "גבעתיים": "Givatayim",
    "בני ברק": "Bnei Brak",
    "פתח תקווה": "Petah Tikva",
    "אור יהודה": "Or Yehuda",
    "יהוד": "Yehud",
    "יהוד-מונוסון": "Yehud-Monosson",
    "אזור": "Azor",
    "בית דגן": "Beit Dagan",
    "קריית אונו": "Kiryat Ono",
    "גבעת שמואל": "Givat Shmuel",
    "סביון": "Savyon",
    "גן יבנה": "Gan Yavne",
    # ── Jerusalem ────────────────────────────────────────────────────
    "ירושלים": "Jerusalem",
    "ירושלים - מרכז": "Jerusalem - Center",
    "ירושלים - צפון": "Jerusalem - North",
    "ירושלים - דרום": "Jerusalem - South",
    "ירושלים - מזרח": "Jerusalem - East",
    "ירושלים - מערב": "Jerusalem - West",
    "מעלה אדומים": "Ma'aleh Adumim",
    "ביתר עילית": "Beitar Illit",
    "גבעת זאב": "Givat Ze'ev",
    "אבו גוש": "Abu Ghosh",
    "מבשרת ציון": "Mevaseret Zion",
    "בית שמש": "Beit Shemesh",
    "זכריה": "Zekharia",
    # ── Haifa & North Coast ──────────────────────────────────────────
    "חיפה": "Haifa",
    "חיפה - כרמל": "Haifa - Carmel",
    "חיפה - מרכז": "Haifa - Center",
    "חיפה - צפון": "Haifa - North",
    "חיפה - דרום": "Haifa - South",
    "נשר": "Nesher",
    "טירת כרמל": "Tirat Carmel",
    "קריית ים": "Kiryat Yam",
    "קריית ביאליק": "Kiryat Bialik",
    "קריית מוצקין": "Kiryat Motzkin",
    "קריית אתא": "Kiryat Ata",
    "עכו": "Acre",
    "נהריה": "Nahariya",
    "שלומי": "Shlomi",
    "כרמיאל": "Karmiel",
    "מעלות-תרשיחא": "Ma'alot-Tarshiha",
    "מעלות": "Ma'alot",
    "חניתה": "Hanita",
    "ראש הנקרה": "Rosh HaNikra",
    "נתיב השיירה": "Netiv HaShayara",
    "לוחמי הגטאות": "Lohamei HaGeta'ot",
    "בנימינה": "Binyamina",
    "זכרון יעקב": "Zichron Ya'akov",
    "עתלית": "Atlit",
    "פרדס חנה-כרכור": "Pardes Hanna-Karkur",
    "חדרה": "Hadera",
    "קיסריה": "Caesarea",
    # ── Sharon / Center-North ────────────────────────────────────────
    "נתניה": "Netanya",
    "הרצליה": "Herzliya",
    "רמת השרון": "Ramat HaSharon",
    "הוד השרון": "Hod HaSharon",
    "כפר סבא": "Kfar Saba",
    "רעננה": "Ra'anana",
    "רמת ישי": "Ramat Yishai",
    "קלנסווה": "Qalansawe",
    "טייבה": "Tayibe",
    "כפר קאסם": "Kafr Qasim",
    "ראש העין": "Rosh HaAyin",
    "אלעד": "El'ad",
    "נס ציונה": "Nes Ziona",
    "ראשון לציון": "Rishon LeZion",
    "חולון": "Holon",
    "בת ים": "Bat Yam",
    "לוד": "Lod",
    "רמלה": "Ramla",
    "מודיעין": "Modi'in",
    "מודיעין-מכבים-רעות": "Modi'in-Maccabim-Re'ut",
    "מודיעין עילית": "Modi'in Illit",
    # ── Shfela / South-Center ────────────────────────────────────────
    "רחובות": "Rehovot",
    "נס ציונה": "Nes Ziona",
    "גדרה": "Gedera",
    "יבנה": "Yavne",
    "באר יעקב": "Be'er Ya'akov",
    "קריית עקרון": "Kiryat Ekron",
    "גן יבנה": "Gan Yavne",
    "מזכרת בתיה": "Mazkeret Batya",
    "פלמחים": "Palmachim",
    "ניצן": "Nitzan",
    "ניצנים": "Nitzanim",
    "אשדוד": "Ashdod",
    "אשדוד - צפון": "Ashdod - North",
    "אשדוד - דרום": "Ashdod - South",
    "אשדוד - מזרח": "Ashdod - East",
    "קריית גת": "Kiryat Gat",
    "קריית מלאכי": "Kiryat Malachi",
    # ── Ashkelon / Lachish ───────────────────────────────────────────
    "אשקלון": "Ashkelon",
    "אשקלון - מרכז": "Ashkelon - Center",
    "אשקלון - צפון": "Ashkelon - North",
    "אשקלון - דרום": "Ashkelon - South",
    "אשקלון - מזרח": "Ashkelon - East",
    "אשקלון - מערב": "Ashkelon - West",
    "אשקלון - נווה גנים": "Ashkelon - Neve Ganim",
    "אשקלון - ברנע": "Ashkelon - Barnea",
    "אשקלון - אפרידר": "Ashkelon - Afridar",
    "אשקלון - גבים": "Ashkelon - Gavim",
    "אשקלון - מיתר": "Ashkelon - Meitar",
    "אשקלון - ממשית": "Ashkelon - Mamshit",
    "אשקלון - רמת אשכול": "Ashkelon - Ramat Eshkol",
    "אשקלון - תחנת כוח": "Ashkelon - Power Station",
    "זיקים": "Zikim",
    "כרמיה": "Carmiya",
    # ── Gaza Envelope (עוטף עזה) ─────────────────────────────────────
    "שדרות": "Sderot",
    "נתיבות": "Netivot",
    "אופקים": "Ofakim",
    "רוחמה": "Ruhama",
    "מגן": "Magen",
    "תקומה": "Tkuma",
    "ברור חיל": "Brur Hayil",
    "בית קמה": "Beit Kama",
    "כוכב מיכאל": "Kokhav Mikha'el",
    "קוממיות": "Komemiut",
    "יד מרדכי": "Yad Mordechai",
    "ניר עוז": "Nir Oz",
    "נחל עוז": "Nachal Oz",
    "כפר עזה": "Kfar Aza",
    "בארי": "Be'eri",
    "רעים": "Re'im",
    "אורים": "Urim",
    "עין השלושה": "Ein HaShlosha",
    "גבים": "Gevim",
    "חולית": "Hulit",
    "ספיר": "Sapir",
    "ניר יצחק": "Nir Yitzhak",
    "ניר אם": "Nir Am",
    "שרשרת": "Sharsheret",
    "גבעות בר": "Givot Bar",
    "אשכול": "Eshkol",
    "מרחבים": "Merhavim",
    "שאר הנגב": "She'ar HaNegev",
    "שדה ניצן": "Sdeh Nitzan",
    "יכיני": "Yakhini",
    "שדי אברהם": "Sdei Avraham",
    "מפלסים": "Mafalasim",
    "כסופים": "Kissufim",
    "שדה עבודה": "Sdeh Avoda",
    "נבטים": "Nevatim",
    "עלומים": "Alumim",
    "חלוץ": "Haluts",
    "כרם שלום": "Kerem Shalom",
    "עין הבשור": "Ein HaBesor",
    "פטיש": "Patish",
    "גמזו": "Gimzo",
    "דורות": "Dorot",
    "גלאון": "Ga'alon",
    # ── Beer Sheva & Negev ───────────────────────────────────────────
    "באר שבע": "Beer Sheva",
    "באר שבע - מרכז": "Beer Sheva - Center",
    "באר שבע - צפון": "Beer Sheva - North",
    "באר שבע - דרום": "Beer Sheva - South",
    "באר שבע - מזרח": "Beer Sheva - East",
    "עומר": "Omer",
    "להבים": "Lehavim",
    "מיתר": "Meitar",
    "ירוחם": "Yeruham",
    "דימונה": "Dimona",
    "ערד": "Arad",
    "מצפה רמון": "Mitzpe Ramon",
    "ניצנה": "Nitzana",
    "רהט": "Rahat",
    "תל שבע": "Tel Sheva",
    "לקיה": "Lakiya",
    "כסייפה": "Ksseife",
    "חורה": "Hura",
    "שגב שלום": "Shagev Shalom",
    "ביר הדאג'": "Bir Hadaj",
    "מולדה": "Mulada",
    "אילת": "Eilat",
    "משמר הנגב": "Mishmar HaNegev",
    "בית קמה": "Beit Kama",
    "שובל": "Shuval",
    "עזוז": "Azuz",
    "בכמה": "Biqah",
    "צאלים": "Tze'elim",
    "ניר ישראל": "Nir Yisrael",
    "שיזף": "Shizaf",
    "אשלים": "Ashalim",
    "רמון": "Ramon",
    "קדש ברנע": "Kadesh Barnea",
    # ── Galilee & North ──────────────────────────────────────────────
    "קריית שמונה": "Kiryat Shmona",
    "מטולה": "Metula",
    "כפר גלעדי": "Kfar Giladi",
    "שניר": "Shnir",
    "אביבים": "Avivim",
    "מנרה": "Manara",
    "ראש פינה": "Rosh Pina",
    "חצור הגלילית": "Hazor HaGlilit",
    "צפת": "Tzfat",
    "עין זיתים": "Ein Zeitim",
    "מירון": "Meron",
    "כפר ורדים": "Kfar Veradim",
    "ביריה": "Biriya",
    "דלתון": "Dalton",
    "אמירים": "Amirim",
    "מג'ד אל-כרום": "Majd al-Krum",
    "שפרעם": "Shfar'am",
    "כפר כנא": "Kafr Kanna",
    "ריינה": "Reineh",
    "נצרת": "Nazareth",
    "נוף הגליל": "Nof HaGalil",
    "נצרת עילית": "Nof HaGalil",
    "יקנעם": "Yokneam",
    "יוקנעם": "Yokneam",
    "כפר יהושע": "Kfar Yehoshua",
    "מגדל העמק": "Migdal HaEmek",
    "עפולה": "Afula",
    "בית שאן": "Beit She'an",
    "גינוסר": "Ginosar",
    "מגדל": "Migdal",
    "טבריה": "Tiberias",
    "כנרת": "Kinneret",
    "דגניה": "Degania",
    "צמח": "Tzemach",
    "עין גב": "Ein Gev",
    "מעגן": "Ma'agan",
    "רמות": "Ramot",
    # ── Golan Heights ───────────────────────────────────────────────
    "קצרין": "Katzrin",
    "אל-רום": "El-Rom",
    "מרום גולן": "Merom Golan",
    "נווה אטיב": "Neve Ativ",
    "מסדה": "Masada",
    "חמת גדר": "Hamat Gader",
    "בני יהודה": "Bnei Yehuda",
    "חספין": "Hispin",
    "אניעם": "Ani'am",
    "נווה אור": "Neve Or",
    # ── Jordan Valley ────────────────────────────────────────────────
    "ירדן": "Jordan Valley",
    "בית שאן": "Beit She'an",
    "מעוז חיים": "Ma'oz Hayyim",
    "טירת צבי": "Tirat Tzvi",
    "שדה אליהו": "Sdeh Eliyahu",
    "כפר רופין": "Kfar Ruppin",
    "ניר דוד": "Nir David",
    "גשר": "Gesher",
    "כינרות": "Kinneret",
    "אפיקים": "Afiqim",
    # ── Judea & Samaria (West Bank settlements) ──────────────────────
    "אריאל": "Ariel",
    "קדומים": "Kedumim",
    "כרני שומרון": "Karnei Shomron",
    "קרני שומרון": "Karnei Shomron",
    "אלפי מנשה": "Alfei Menashe",
    "שומרון": "Samaria",
    "שכם": "Nablus area",
    "בית אריה": "Beit Arye",
    "עופרים": "Ofarin",
    "עלי": "Eli",
    "שילה": "Shiloh",
    "עפרה": "Ofra",
    "בית אל": "Beit El",
    "פסגות": "Psagot",
    "כוכב יעקב": "Kokhav Ya'akov",
    "אדם": "Adam",
    "גבעה בנימין": "Giv'ah Binyamin",
    "מכמש": "Michmash",
    "ענתות": "Anatot",
    "גוש עציון": "Gush Etzion",
    "אפרת": "Efrat",
    "אלון שבות": "Alon Shvut",
    "בת עין": "Bat Ayin",
    "הר גילה": "Har Gilo",
    "קריית ארבע": "Kiryat Arba",
    "חברון": "Hebron area",
    "גנות": "Ganot",
    # ── Coastal Plain ────────────────────────────────────────────────
    "גן שמואל": "Gan Shmuel",
    "כפר הנגיד": "Kfar HaNagid",
    "כפר אביב": "Kfar Aviv",
    "ברנר": "Brenner",
    "גדרות": "Gederot",
    "שדה משה": "Sdeh Moshe",
    "מצליח": "Matzliah",
    "שורש": "Shoresh",
    "שוהם": "Shoham",
    "כפר חבד": "Kfar Chabad",
    "סגולה": "Segula",
    "גן חיים": "Gan Hayyim",
    "אחיטוב": "Ahituv",
    "תנובות": "Tenuvot",
    "בית חנניה": "Beit Hananya",
    "בית יצחק": "Beit Yitzhak",
    "בית ברל": "Beit Berl",
    "כפר מל'ל": "Kfar Malal",
    "אבן יהודה": "Even Yehuda",
    "כפר נטר": "Kfar Netter",
    "גבעת חיים": "Givat Hayyim",
    "עין ורד": "Ein Vered",
    "תל מונד": "Tel Mond",
    "נעמה": "Na'ama",
    "רשפון": "Rishpon",
    "גבעת חן": "Givat Hen",
    "גני עם": "Ganei Am",
    "קיבוץ גלויות": "Kibbutz Galuyot",
    "כפר שמריהו": "Kfar Shmaryahu",
    "רמת פולג": "Ramat Poleg",
    "אמנון ותמר": "Amnon VeTamar",
    "עמיקם": "Amikam",
    "עדי": "Adi",
    "עין השופט": "Ein HaShofet",
    "גבעת עדה": "Givat Ada",
    "גן שורק": "Gan Sorek",
    "ניר צבי": "Nir Tzvi",
    "צפריה": "Tzafriya",
    "יסודות": "Yesodot",
    "שדמות דבורה": "Shdamot Devora",
    # ── Misc / Regional Councils ─────────────────────────────────────
    "אשתאול": "Eshtaol",
    "תענך": "Ta'anakh",
    "מגידו": "Megiddo",
    "יפיע": "Yafia",
    "ירכא": "Yirka",
    "בוסתן הגליל": "Bustan HaGalil",
    "געתון": "Ga'aton",
    "ברעם": "Bar'am",
    "שאר ישוב": "She'ar Yashuv",
    "מחניים": "Mahanayim",
    "יסוד המעלה": "Yesod HaMa'ala",
    "עין מאהל": "Ein Mahel",
    "דבוריה": "Daburiyya",
    "ג'לג'וליה": "Jaljulya",
    "ירכא": "Yirka",
    "זמר": "Zemer",
    "בארותיים": "Be'erotayim",
    "כפר יסיף": "Kafr Yasif",
    "ג'ת": "Jatt",
    "ערערה": "Ar'ara",
    "כפר מנדא": "Kafr Manda",
    "דייר אל-אסד": "Deir al-Asad",
    "בועינה-נוג'ידאת": "Bu'eine-Nujeidat",
    "שעב": "Sha'ab",
    "עין יפה": "Ein Yafa",
    "מג'ד אל-כרום": "Majd al-Krum",
    "עספיה": "Isfiya",
    "דאלית אל-כרמל": "Daliyat al-Carmel",
    "ג'סר א-זרקא": "Jisr az-Zarqa",
    "קיסריה": "Caesarea",

    # ── Sharon / Central plain additions ─────────────────────────────
    "פרדס חנה": "Pardes Hanna",
    "פרדס חנה-כרכור": "Pardes Hanna-Karkur",
    "גני תקווה": "Ganei Tikva",
    "יהוד מונוסון": "Yehud-Monosson",
    "רינתיה": "Rinnatia",
    "נחלים": "Nahalim",
    "בני עטרות": "Bnei Atarot",
    "בארות יצחק": "Be'erot Yitzhak",
    "גת רימון": "Gat Rimon",
    "מזור": "Mazor",
    "נופך": "Nofech",
    "כפר טרומן": "Kfar Truman",
    "טירת יהודה": "Tirat Yehuda",
    "גבעת השלושה": "Givat HaShelosha",
    "בן שמן": "Ben Shemen",
    "עינת": "Einat",
    "כפר נוער בן שמן": "Ben Shemen Youth Village",
    "כפר סירקין": "Kfar Sirkin",
    "גינתון": "Ginaton",
    "עיינות": "Einot",
    "בית עובד": "Beit Oved",
    "אחיסמך": "Ahisamach",
    "גבעת כ''ח": "Givat Koah",
    "ישרש": "Yashrash",
    "נחשונים": "Nachshonim",
    "איירפורט סיטי": "Airport City",
    "כפר דניאל": "Kfar Daniel",
    "גן שלמה": "Gan Shlomo",
    "גני הדר": "Ganei Hadar",
    "גאליה": "Ga'alia",
    "יד רמב''ם": "Yad Rambam",
    "כפר ביל''ו": "Kfar Bilu",
    "רמות מאיר": "Ramot Meir",
    "כפר שמואל": "Kfar Shmuel",
    "גזר": "Gezer",
    "בית חשמונאי": "Beit Hashmonai",
    "עזריה": "Azarya",
    "בית עוזיאל": "Beit Uziel",
    "יציץ": "Yatzitz",
    "משמר איילון": "Mishmar Ayalon",
    "נילי": "Nili",
    "יערה": "Ya'ara",
    "פדיה": "Pedaya",
    "פתחיה": "Petahia",
    "גני יוחנן": "Ganei Yohanan",
    "חשמונאים": "Hashmonaim",
    "שילת": "Shilat",
    "כפר בן נון": "Kfar Bin Nun",
    "לפיד": "Lapid",
    "כפר האורנים": "Kfar HaOranim",
    "מתתיהו": "Mattityahu",
    "נעלה": "Na'aleh",
    "כרמי יוסף": "Karmi Yosef",
    "לימן": "Liman",
    "מבוא מודיעים": "Mevo Modi'im",
    "נאות קדומים": "Ne'ot Kedumim",
    "מגשימים": "Magshimim",
    "זיתן": "Zeitan",
    "בית חנן": "Beit Hanan",
    "מעש": "Ma'as",
    "נטעים": "Neta'im",
    "יגל": "Yagel",
    "ברקת": "Bareket",
    "בית נחמיה": "Beit Nehemia",
    "חדיד": "Hadid",
    "סתריה": "Sataria",
    "אירוס": "Irus",
    "נצר סרני": "Netzar Sereni",
    "בית עריף": "Beit Arif",
    "גיבתון": "Givton",
    "נען": "Na'an",
    "פדואל": "Peduel",
    "מודיעין מכבים רעות": "Modi'in-Maccabim-Re'ut",

    # ── Shephelah / Coastal plain ─────────────────────────────────────
    "חמד": "Hemed",
    "מקווה ישראל": "Mikveh Israel",
    "איבים": "Ivim",
    "אחיעזר": "Ahiezer",
    "נתיב העשרה": "Netiv HaAsara",
    "משמר השבעה": "Mishmar HaShiva",
    "ניר עם": "Nir Am",
    "גיבתון": "Givton",
    "בית הלל": "Beit Hillel",
    "בצת": "Batzat",
    "גן שורק": "Gan Sorek",

    # ── Galilee / North ───────────────────────────────────────────────
    "משגב עם": "Misgav Am",
    "מרגליות": "Margaliot",
    "תל חי": "Tel Hai",
    "כפר יובל": "Kfar Yuval",
    "ערב אל עראמשה": "Arab al-Aramshe",
    "כפר חב''ד": "Kfar Chabad",

    # ── Industrial zones & special sites ─────────────────────────────
    "אזור תעשייה הדרומי אשקלון": "Ashkelon Southern Industrial Zone",
    "פארק תעשיות פלמחים": "Palmachim Industrial Park",
    "תעשיון צריפין": "Tzrifin Industrial Zone",
    "אזור תעשייה נשר - רמלה": "Nesher-Ramle Industrial Zone",
    "אזור תעשייה אפק ולב הארץ": "Afek and Lev HaAretz Industrial Zone",
    "מתחם פי גלילות": "Pi Glilot Complex",
    "בית עלמין מורשה": "Morasha Cemetery",
    "מרינה": "Marina",
}
